version: "3"

services:
  troposphere:
    image: connected-places/backend/troposphere
    build:
      context: ./docker/troposphere
      dockerfile: Dockerfile
    volumes:
      - ./aws:/tmp
    command: "python ${CFN_TEMPLATE}.py"
